[package]
name = "intron"
version = "0.18.9"
description = "A toolchain manager for C++"
authors = ["Geunryeol Park (misut)"]
license = "MIT"
type = "bin"
standard = 23

[dependencies]
"github.com/misut/tomlcpp" = "0.3.0"

[dependencies.path]
cppx = "/Users/kakao/Private/.worktrees/cppx/feat/shared-edge-primitives"

[target.'cfg(os = "linux")'.build]
ldflags = ["-lssl", "-lcrypto"]

[target.'cfg(os = "macos")'.build]
ldflags = ["-framework", "Security", "-Wl,-framework,CoreFoundation"]
