[package]
name = "intron"
version = "0.11.0"
description = "A toolchain manager for C++"
authors = ["Geunryeol Park (misut)"]
license = "MIT"
type = "bin"
standard = 23

[dependencies]
"github.com/misut/tomlcpp" = "0.1.0"
