[package]
name = "intron"
version = "0.18.2"
description = "A toolchain manager for C++"
authors = ["Geunryeol Park (misut)"]
license = "MIT"
type = "bin"
standard = 23

[dependencies]
"github.com/misut/cppx" = "0.3.1"
"github.com/misut/tomlcpp" = "0.3.0"
